inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.gemfile'
    - '**/*.gemspec'
  Exclude:
    - 'lib/sequel-rails.rb'
    - 'ci/**/*'

HashSyntax:
  EnforcedStyle: hash_rockets

